In [2]:
import numpy as np

In [4]:
x = np.array([[1.0,-0.5],
              [-2.0,3.0]])

In [6]:
print(x)

[[ 1.  -0.5]
 [-2.   3. ]]


In [12]:
mask = (x<=0)

In [14]:
mask

array([[False,  True],
       [ True, False]])

In [16]:
X = np.random.rand(2)
X

array([0.70089144, 0.69393553])

In [18]:
W = np.random.rand(2,3)
W

array([[0.77063478, 0.80394214, 0.84202605],
       [0.29474632, 0.64259225, 0.17157214]])

In [20]:
B = np.random.rand(3)
B

array([0.48799979, 0.76199761, 0.59708647])

In [22]:
X.shape

(2,)

In [24]:
W.shape

(2, 3)

In [26]:
B.shape

(3,)

In [28]:
T = np.dot(X,W) + B

In [30]:
T

array([1.23266605, 1.77139138, 1.30631533])

In [32]:
X_dot_W = np.array([[0,0,0],
                    [10,10,10]])

In [34]:
B = np.array([1,2,3])

In [36]:
X_dot_W

array([[ 0,  0,  0],
       [10, 10, 10]])

In [38]:
B

array([1, 2, 3])

In [40]:
X_dot_W + B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [44]:
dY = np.array([[1,2,3],
               [4,5,6]])
dY

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
dB = np.sum(dY,axis = 0)
dB

array([5, 7, 9])