In [2]:
import numpy as np

In [3]:
W = np.arange(21).reshape(7,3)

In [4]:
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [5]:
W[2]

array([6, 7, 8])

In [6]:
W[5]

array([15, 16, 17])

In [7]:
idx = np.array([1,0,3,0])

W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])

In [1]:
import numpy as np

In [2]:
np.random.choice(10)

8

In [9]:
np.random.choice(10)

5

In [10]:
words = ['you','say','goodbye','I','hello','.']
np.random.choice(words)

np.str_('.')

In [11]:
np.random.choice(words,size = 5)

array(['.', 'you', 'hello', 'I', '.'], dtype='<U7')

In [14]:
np.random.choice(words,size = 5,replace = False)

array(['goodbye', 'you', '.', 'hello', 'I'], dtype='<U7')

In [18]:
p = [0.5,0.1,0.05,0.2,0.05,0.1]
np.random.choice(words,p = p)
#没有p按照均匀概率抽取
#p的和为1,p的形状和words形状需要一样,对应元素概率与p对应

np.str_('you')

In [23]:
p = [0.7,0.29,0.01]
new_p = np.power(p,0.75)
new_p /= np.sum(new_p)
new_p

array([0.64196878, 0.33150408, 0.02652714])