In [2]:
import numpy as np

In [3]:
W = np.arange(21).reshape(7,3)

In [4]:
W

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [5]:
W[2]

array([6, 7, 8])

In [6]:
W[5]

array([15, 16, 17])

In [7]:
idx = np.array([1,0,3,0])

W[idx]

array([[ 3,  4,  5],
       [ 0,  1,  2],
       [ 9, 10, 11],
       [ 0,  1,  2]])